Add .tapFailure to TryOps
AVSystem/scala-commons pull request #609
Opened 2024-07-26 10:55 UTC by najder-k

- works basically like `tapError` on Task
- used to avoid doing `failed.foreach` on task, which creates an unnecessary exception on Try.Success

2024-07-29 05:25 UTC, ddworak requested changes

2024-07-29 05:25 UTC, ddworak commented on core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
> +        action(throwable)
What do you want to do when `action(throwable)` throws an exception? Not sure if current choice would be my default, but I'd like to hear your thoughts first. Please document your choice as well.

2024-07-29 13:54 UTC, ddworak commented on core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
> +        action(throwable)
My thoughts were that any `.tap` method should never alter the result. The libraries are also on the fence: `Task#tapError` handles, `Flow#wireTap` I think too but `Iterator#tapEach` and `Observable#doOnNext` do not. I'd probably replicate `Task` approach and use the same name, but I'm okay with other behaviour if it's documented and tested.

2025-06-20 19:14 UTC, halotukozak commented on core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
> +        action(throwable)
fixed with catching nonfatal exception. Tests added. Can we proceed this MR?

2025-06-24 16:07 UTC, najder-k commented on core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
> +        action(throwable)
You actually went for the 'tap should never alter the result' way, but tbh I'm fine with it too (after some time passed, probably even more than with the `Task#tapError` approach)

Since it's more your MR than mine at this point, I'll take over the review :D

2025-06-24 16:17 UTC, ddworak commented on core/src/test/scala/com/avsystem/commons/misc/SharedExtensionsTest.scala
>  }
missing test for fatal exception

2025-06-24 16:18 UTC, ddworak commented on core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
> +      * Don't use .failed projection here, because it unnecessarily creates Exception in case of Success,
nit: `here` is ambiguous here, I initally thought I should not use it on the result

2025-06-24 16:19 UTC, ddworak commented on core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
> +      *
a few more words on the semantics regarding `action`?

2025-06-25 07:33 UTC, ddworak requested changes

2025-06-25 07:33 UTC, ddworak commented on core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
> +      * Any exceptions thrown by the `action` function are caught and ignored, ensuring that this method
This is not true. You've literally just added a test that shows it's not all exceptions.

2025-06-25 08:41 UTC, ddworak approved these changes

2025-06-25 09:03 UTC, merged