Allow Output to ignore @transientDefault
AVSystem/scala-commons pull request #633
Opened 2024-09-21 15:33 UTC by sebaciv

Implement `IgnoreTransientDefaultMarker` that allows `Output` implementation to instruct `GenCodec` instance to ignore
`@transientDefault` annotation on case class fields and serialize all fields even when field value is equal to it's default value.

2024-09-25 09:44 UTC, halotukozak requested changes

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +          (acc, p) => q"$acc + (if(${accessor(p)} == ${transientValue(p)}) 1 else 0)"
nit: space after `if`

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +          q"if($checkIgnoreTransientDefaultMarker) ${countOnlyOptionLike(accessor)} else ${countTransient(accessor)}"
nit: space after `if`

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +          q"if(!$checkIgnoreTransientDefaultMarker && $value == ${transientValue(param)}) 1 else 0"
nit: space after `if`

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +          q"if($value == ${transientValue(param)}) 1 else 0"
nit: space after `if`

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +              if(unapplyRes.isEmpty) unapplyFailed else { ${countSingleParam(p, q"unapplyRes.get")} }
nit: space after `if`

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +              if(unapplyRes.isEmpty) unapplyFailed else {
nit: space after `if`

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +                val t = unapplyRes.get
also you can match on `Option`

2024-09-25 09:44 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +            if (unapplyRes.isEmpty) unapplyFailed
also can match on `Option`

2024-09-25 09:49 UTC, ddworak commented on core/src/main/scala/com/avsystem/commons/serialization/customMarkerWrappers.scala
> +    marker match {
`if (...) true` is an or

2024-09-25 09:51 UTC, halotukozak commented on core/src/main/scala/com/avsystem/commons/serialization/customMarkerWrappers.scala
> +    marker match {
even better xD

2024-09-25 13:17 UTC, sebaciv commented on core/src/main/scala/com/avsystem/commons/serialization/GenCodec.scala
> +    def size(value: T): Int = size(value, Opt.Empty)
I'm not sure what is the best solution here. I'm worried about binary-compatibility (is it even possible to provide it?). Problem: there is an older version of commons-core on the classpath of another library with macro generated codec for some class that has only `def size(value: T): Int` implemented.

@ddworak any advise here?

2024-09-25 13:22 UTC, sebaciv commented on core/src/main/scala/com/avsystem/commons/serialization/customMarkerWrappers.scala
> +object CustomMarkersOutputWrapper {
`SequentialOutputWrapper` is a superclass of `ListOutputWrapper` and `ObjectOutputWrapper`

2024-09-25 13:26 UTC, sebaciv commented on core/src/test/scala/com/avsystem/commons/serialization/IgnoreTransientDefaultMarkerTest.scala
> +  test("write case class with opt values") {
I assumed all option-like types are treated the same by com.avsystem.commons.serialization.optionalParam, so there should be no need to write test for every type.

2024-09-25 13:34 UTC, sebaciv commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +          val ignoreTransientDefault = $ignoreTransientDefaultCheck
To avoid calling output.customEvent multiple times

2024-09-25 13:43 UTC, sebaciv commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +      val transientValue = p.optionLike.map(ol => q"${ol.reference(Nil)}.none")
OptionLike I guess

2024-09-25 13:53 UTC, sebaciv commented on core/src/main/scala/com/avsystem/commons/serialization/customMarkerWrappers.scala
> +object CustomMarkersInputWrapper {
Same as `SequentialOutputWrapper`, it is superclass

2024-09-26 07:08 UTC, halotukozak commented on macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
> +              if(unapplyRes.isEmpty) unapplyFailed else {
ofc, so it's only a nit

2024-09-26 07:10 UTC, ddworak commented on core/src/main/scala/com/avsystem/commons/serialization/GenCodec.scala
> +    def size(value: T): Int = size(value, Opt.Empty)
Well, if you call the new `def size(value: T, output: Opt[SequentialOutput]): Int` from the outside, then it's not possible for classes compiled under old commons. If you choose other implementation path than adding new method - maybe, but I don't have the time to grab the context and not delay you :) In other cases, see https://contributors.scala-lang.org/t/can-we-make-adding-a-parameter-with-a-default-value-binary-compatible/6132 and https://www.youtube.com/watch?v=2wkEX6MCxJs

2024-09-26 14:03 UTC, halotukozak commented
LGTM

2024-09-26 14:03 UTC, halotukozak approved these changes

2024-09-27 08:37 UTC, sebaciv commented on core/src/main/scala/com/avsystem/commons/serialization/GenCodec.scala
> +    def size(value: T): Int = size(value, Opt.Empty)
Very nice idea with `@unroll`, but unfortunately not implemented yet :/

I don't see way to change implementation in a compatible way. Outputs relying in `size` will be affected (so basically only CBOR ? ), so maybe it won't be problem?

2024-09-30 13:27 UTC, merged